export const QUERIES = {
  // EVENTS
  LIST_EVENTS: "LIST_EVENTS",
  LIST_EVENTS_PUBLIC: "LIST_EVENTS_PUBLIC",

  // USER
  PROFILE_INFOS: "PROFILE_INFOS"
};

export const ADM_QUERIES = {
  // MEMBROS
  LIST_MEMBROS_ADM: "LIST_MEMBROS_ADM",

  // EVENTS
  LIST_EVENTS_ADM: "LIST_EVENTS_ADM",

  // DONATIONS
  LIST_DONATIONS_ADM: "LIST_DONATIONS_ADM",

  // MINISTERIOS
  LIST_MINISTERIOS_ADM: "LIST_MINISTERIOS_ADM",
};
